<a href="https://colab.research.google.com/github/OscarRojasG/Experimentos-EvaluAI/blob/main/Framework_EvaluAI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Implementación

## Cargar dataset y librerías necesarias

In [1]:
!pip install openai==0.28 &> /dev/null
!pip install openai-multi-client &> /dev/null
!pip install plotly
!git clone https://github.com/rilianx/GPTEvaluator &> /dev/null

Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly) (8.5.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly) (25.0)

In [2]:
import pandas as pd
from IPython.display import display

# Muestra información relevante del dataset
def show_dataset_info(dataset):
    display(dataset.head())
    print()
    print(dataset.value_counts("real_eval"), end="\n\n")
    print(dataset.value_counts("dataset"))
    pass

# Carga un dataset a partir de un archivo xlsx y valida sus columnas
def load_dataset(path, sheet_name, column_data):
    df = pd.read_excel(path, sheet_name=sheet_name)

    mandatory_cols = ["context", "question", "answer", "real_eval", "dataset"]
    for key in mandatory_cols:
        if key not in column_data.keys():
            raise Exception(f"Error: Debe especificar la columna para la variable {key}")

        value = column_data[key]
        if value not in df.columns:
            raise Exception(f"Error: La columna {value} no existe")

        df = df.rename(columns={value: key})

    df = df[mandatory_cols]
    df['row'] = df.index + 2
    show_dataset_info(df)
    return df

## Generación prompts

In [3]:
import pprint
import copy
import json
import os
import re

class Prompt():
    def __init__(self, structure, instructions, base_folder):
        self.structure = structure
        self.instructions = instructions
        self.base_folder = base_folder
        self.raw_text_structure = None
        self.text_structure = None
        self.criteria = None
        self.output_instructions = None
        self.prompt = None

        self.read_files()
        self.extract_metadata()
        self.build_prompt()

    # Retorna la estructura base del prompt (diccionario)
    def base_structure(self):
        structure = copy.deepcopy(self.structure)
        structure['instructions'] = {}
        for i in self.instructions:
            structure['instructions'][i] = structure[i]
            structure.pop(i, None)
        return structure

    # Crea un diccionario con el contenido de cada archivo en la estructura
    def read_files(self):
        self.raw_text_structure = copy.deepcopy(self.structure)

        for key, value in self.raw_text_structure.items():
            if key == "instructions": continue

            path = f"{self.base_folder}/{key}/{value}"
            try:
                self.raw_text_structure[key] = open(path, 'r', encoding='utf-8').read()
                self.raw_text_structure[key] += "\n\n"
            except:
                raise Exception(f"Error: El archivo {path} no existe")

    # Extrae metadatos de los archivos como los criterios e instrucciones de salida
    def extract_metadata(self):
        self.text_structure = copy.deepcopy(self.raw_text_structure)
        self.output_instructions = {}
        self.criteria = []

        for key in self.text_structure:
            value = self.text_structure[key]

            if value.startswith('#') and not value.startswith('##'):
                m = re.search(r'#(.*?)\n', value).group(1)
                mkey, mvalue = m.split(":", 1)
                self.output_instructions[mkey.lstrip()] = mvalue.lstrip()
                self.text_structure[key] = '\n'.join(value.split('\n')[1:])

            if key == 'score':
                lines = self.text_structure['score'].split('\n')
                for line in lines:
                    if line.startswith('$'):
                        m = re.search(r'\$(.*?)\n', value).group(1)
                        mkey, mvalue = m.split(":", 1)

                        self.criteria.append(mkey.lstrip())
                        self.output_instructions[mkey.lstrip()] = mvalue.lstrip()
                        self.text_structure[key] = '\n'.join(value.split('\n')[1:])


    # Construye el prompt en formato string
    def build_prompt(self):
        self.prompt = ""
        for key, value in self.text_structure.items():
            self.prompt += value

        output = self.build_output()
        self.prompt += output

    def build_output(self):
        output = "I expect a dict in python as answer: {{"
        output += ', '.join(f'"{key}": \'{value}\'' for key, value in self.output_instructions.items())

        output += "}}\n\nPython dict:"
        return output


# Procesa y elimina los diccionarios anidados de prompt_data
def normalize_prompt_dict(prompt_data):
    instructions = []
    after_instructions = {}
    found_target = False

    if "instructions" in prompt_data:
        for key, value in prompt_data.items():
            if found_target:
                after_instructions[key] = value
            if key == "instructions":
                found_target = True

        for (key, value) in prompt_data["instructions"].items():
            prompt_data[key] = value
            instructions.append(key)

        for key, value in after_instructions.items():
            del prompt_data[key]
            prompt_data[key] = value

    prompt_data["instructions"] = "Instructions:\n"
    return prompt_data, instructions

# Retorna la lista de archivos para reemplazar el comodín *
def expand_prompt_data(prompt_data, prompt_folder):
    wildcard_field = None
    for key, value in prompt_data.items():
        if value == "*":
            wildcard_field = key
            break

    if not wildcard_field: return None, None

    wildcard_files = []
    path = f"{prompt_folder}/{wildcard_field}"
    for file in sorted(os.listdir(path)):
        if os.path.isfile(os.path.join(path, file)):
            wildcard_files.append(file)

    return wildcard_field, wildcard_files

# Genera una lista con los prompts a evaluar
def generate_prompts(prompt_data, prompt_folder, visualize=True):
    template, instructions = normalize_prompt_dict(prompt_data)
    wildcard_field, wildcard_files = expand_prompt_data(template, prompt_folder)
    prompts = []

    if wildcard_field == None:
        prompt = Prompt(template, instructions, prompt_folder)
        prompts.append(prompt)

        if visualize: print(prompt.prompt)
        return prompts

    for file in wildcard_files:
        structure = copy.deepcopy(template)
        structure[wildcard_field] = file
        prompt = Prompt(structure, instructions, prompt_folder)
        prompts.append(prompt)

    # Visualizar
    if visualize:
        template = copy.deepcopy(prompts[0])
        template.raw_text_structure[wildcard_field] = f"{{{wildcard_field}}}\n\n"
        template.extract_metadata()
        template.build_prompt()
        print(template.prompt)

        print(f"\n\nArchivos a utilizar ({len(wildcard_files)}):\n")
        print("\n".join(wildcard_files))

    return prompts

## Optimización parámetros

In [4]:
from scipy.optimize import differential_evolution
from abc import ABC, abstractmethod
import numpy as np

class ScoreWeighter():
    @staticmethod
    def eval(x, theta, right_offset):
        return np.dot(x, theta[:-right_offset])

class MapOptimizer(ABC):
    def __init__(self, map_params_size):
        self.map_params_size = map_params_size

    def optimize(self, criteria_scores, real_scores):
        bounds =  [(0, 1) for _ in range(len(criteria_scores[0]))] + [(0, 10)] * self.map_params_size
        result = differential_evolution(self.error, bounds, args=(criteria_scores, real_scores), seed=1, strategy='rand1exp', mutation=(0,1), recombination=1)
        return result.x.tolist()

    def error(self, theta, x, y):
        y_pred = self.f(x, theta)
        mse = np.sum((y - y_pred) ** 2)

        # Penalización cuando suma de ponderaciones != 1
        weights = theta[:-self.map_params_size]
        penalty = 1e6 * np.abs(np.sum(weights) - 1)

        # Penalización cuando parámetros de mapeo no están de menor a mayor
        map_params = theta[-self.map_params_size:]
        penalty += sum((map_params[i] - map_params[i+1]) * 1e5 for i in range(len(map_params)-1) if map_params[i] > map_params[i+1])
        return mse + penalty

    @abstractmethod
    def f(self, x, theta):
        pass

class MapOptimizer4(MapOptimizer):
    def __init__(self):
        super().__init__(4)

    def map_array(self, w_scores, theta):
        a, b, c, d = theta[-4:]
        def map(x):
            if x <= a:
                return 0
            if a < x <= b:
                return (x - a) / (b - a)
            if b < x <= c:
                return 1 + (x - b) / (c - b)
            if c < x <= d:
                return 2 + (x - c) / (d - c)
            else:
                return 3
        return np.array([map(x) for x in w_scores])

    def f(self, x, theta):
        w_scores = ScoreWeighter.eval(x, theta, 4)
        return self.map_array(w_scores, theta)

class MapOptimizer2(MapOptimizer):
    def __init__(self):
        super().__init__(2)

    def map_array(self, w_scores, theta):
        a, b = theta[-2:]
        def map(x):
            if x <= a:
                return x / a
            if a < x <= b:
                return 1 + (x - a) / (b - a)
            else:
                return 2 + (x - b) / (10 - b)
        return np.array([map(x) for x in w_scores])

    def f(self, x, theta):
        w_scores = ScoreWeighter.eval(x, theta, 2)
        return self.map_array(w_scores, theta)

class MapOptimizer2Simple(MapOptimizer):
    def __init__(self):
        super().__init__(2)

    def map_array(self, w_scores, theta, eps=1e-9):
        a, b = theta[-2:]
        def map(x):
            if x <= a:
                return x*eps
            if a < x <= b:
                return 3 * (x - a) / (b - a)
            else:
                return 3 + x*eps
        return np.array([map(x) for x in w_scores])

    def f(self, x, theta):
        w_scores = ScoreWeighter.eval(x, theta, 2)
        return self.map_array(w_scores, theta)

class MapOptimizer2Mini(MapOptimizer):
    def __init__(self):
        super().__init__(1)

    def map_array(self, w_scores, theta):
        a = theta[-1]
        def map(x):
            b = 10 - a
            if x <= a:
                return 0
            if a < x <= b:
                return 3 * (x - a) / (b - a)
            else:
                return 3
        return np.array([map(x) for x in w_scores])

    def f(self, x, theta):
        w_scores = ScoreWeighter.eval(x, theta, 1)
        return self.map_array(w_scores, theta)

class MapOptimizer4Mini(MapOptimizer):
    def __init__(self):
        super().__init__(3)

    def map_array(self, w_scores, theta):
        a, b, c = theta[-3:]
        def map(x):
            d = 10 - a
            if x <= a:
                return 0
            if a < x <= b:
                return (x - a) / (b - a)
            if b < x <= c:
                return 1 + (x - b) / (c - b)
            if c < x <= d:
                return 2 + (x - c) / (d - c)
            else:
                return 3
        return np.array([map(x) for x in w_scores])

    def f(self, x, theta):
        w_scores = ScoreWeighter.eval(x, theta, 3)
        return self.map_array(w_scores, theta)

# Obtiene los parámetros óptimos para disminuir el error
def optimize_params(criteria_scores, real_scores, eval_function):
    if eval_function == "map4":
        params = MapOptimizer4().optimize(criteria_scores, real_scores)
    if eval_function == "map4-mini":
        params = MapOptimizer4Mini().optimize(criteria_scores, real_scores)
    if eval_function == "map2" or eval_function == "map":
        params = MapOptimizer2().optimize(criteria_scores, real_scores)
    if eval_function == "map2-simple":
        params = MapOptimizer2Simple().optimize(criteria_scores, real_scores)
    if eval_function == "map2-mini":
        params = MapOptimizer2Mini().optimize(criteria_scores, real_scores)

    return params

# Obtiene los parámetros óptimos para disminuir el error
def convert_gpt_scores(criteria_scores, real_scores, eval_function, eval_params):
    if eval_function == "map4":
        return MapOptimizer4().f(criteria_scores, eval_params)
    if eval_function == "map4-mini":
        return MapOptimizer4Mini().f(criteria_scores, eval_params)
    if eval_function == "map2" or eval_function == "map":
        return MapOptimizer2().f(criteria_scores, eval_params)
    if eval_function == "map2-simple":
        return MapOptimizer2Simple().f(criteria_scores, eval_params)
    if eval_function == "map2-mini":
        return MapOptimizer2Mini().f(criteria_scores, eval_params)

In [6]:
criteria_scores = [[9], [8], [4]]
real_scores = [3, 2, 1]
eval_function = "map4"

eval_params = optimize_params(criteria_scores, real_scores, eval_function)
print(eval_params)
convert_gpt_scores(criteria_scores, real_scores, eval_function, eval_params)

[1.0, 1.1720268471946058, 3.9999999999999996, 8.0, 8.972909085620861]

array([3., 2., 1.])

In [8]:
criteria_scores = [[8, 9, 7], [8, 5, 3], [4, 1, 8]]
real_scores = [3, 2, 1]
eval_function = "map4"

eval_params = optimize_params(criteria_scores, real_scores, eval_function)
print(eval_params)
convert_gpt_scores(criteria_scores, real_scores, eval_function, eval_params)

[0.4287267016646835, 0.20566060222218852, 0.365612696113128, 1.941605522917902, 4.845468977785947, 5.5549547127677945, 7.3527984526670185]

array([3., 2., 1.])

## Experimentos

In [9]:
import random
from GPTEvaluator.GPTEvaluator import chat_gpt_multiple
import matplotlib.pyplot as plt
import plotly.graph_objects as go
from openai_multi_client import OpenAIMultiClient
import openai
from google.colab import userdata
from sklearn.metrics import mean_squared_error
import os
from datetime import datetime, timedelta
import json
import numpy
import plotly.express as px
from plotly.colors import sample_colorscale
import pytz
from sklearn.metrics import mean_absolute_error, r2_score, accuracy_score, precision_score, recall_score, f1_score
from scipy.stats import spearmanr

openai.api_key = userdata.get('OPENAI_API_KEY')

# Retorna un conjunto de datos de entrenamiento o prueba
def generate_set(dataset, set_size, seed=42, balance=False, exclude_set=None):
    random.seed(seed)

    group_size = set_size // 4  # Tamaño grupo para set balanceado
    proportions = df['real_eval'].value_counts(normalize=True)  # Para set no balanceado
    samples_per_class = (proportions * set_size).round().astype(int)

    # Crear set excluyendo las filas de exclude_set
    final_set = dataset
    if exclude_set is not None:
        final_set = dataset[~dataset['row'].isin(exclude_set['row'])]

    if balance:
        final_set = final_set.groupby('real_eval', group_keys=False)[df.columns.tolist()].apply(
            lambda x: x.sample(group_size, random_state=random.randint(0, 100000))
        )
    else:
        final_set = final_set.groupby('real_eval', group_keys=False)[df.columns.tolist()].apply(
            lambda x: x.sample(samples_per_class[x.name], random_state=random.randint(0, 100000))
        )

    return final_set

# Genera las respuestas con ChatGPT
def eval_gpt(df, prompt, criteria, model, temperature):
    df_copy = df.copy()
    api = OpenAIMultiClient(endpoint="chats", data_template={"model": model, "temperature": temperature, "n": 1, "timeout":10}, concurrency=50, wait_interval=1, max_retries=3, retry_max=10, retry_multiplier=1)

    texts = []
    for i, row in df_copy.iterrows():
        text = prompt.format(Question=row['question'], Answer=row['answer'], Context=row['context'])
        texts.append(text)

    answers_gpt = chat_gpt_multiple(api, texts)
    gpt_dicts = extract_dicts(answers_gpt)
    clean_set(df_copy, gpt_dicts, criteria)
    df_dicts = pd.DataFrame(gpt_dicts)
    response_set = pd.concat([df_copy, df_dicts.set_index(df_copy.index)], axis=1)
    return response_set

# Extrae diccionario de salida de las respuestas GPT
def extract_dicts(answers_gpt):
    pattern = r'\{[^{}]+\}'

    gpt_dicts = []
    for answer_gpt in answers_gpt:
        try:
            answer = re.findall(pattern, answer_gpt[0])[0]
            gpt_dicts.append(eval(answer))
        except Exception as e:
            print(f"Error al extraer diccionario. Respuesta GPT: \n{answer_gpt[0]}\n\n")
            gpt_dicts.append(None)

    return gpt_dicts

# Elimina filas del dataset donde hubo errores en la salida GPT
def clean_set(dataset, gpt_dicts, criteria):
    for i in reversed(range(len(gpt_dicts))):
        if gpt_dicts[i] is None:
            gpt_dicts.pop(i)
            dataset.drop(dataset.index[i], inplace=True)
        elif all(key in gpt_dicts[i] for key in criteria) == False:
            print(gpt_dicts[i])
            gpt_dicts.pop(i)
            dataset.drop(dataset.index[i], inplace=True)

# Obtiene los puntajes reales de un dataset
def get_real_scores(dataset):
    return dataset['real_eval'].tolist()

# Prepara el set de entrenamiento y obtiene los parámetros óptimos para disminuir el error
def train(train_set, prompt, criteria, eval_function, model, temperature):
    train_set = train_set.copy()
    res_df = eval_gpt(train_set, prompt, criteria, model, temperature)

    real_scores = get_real_scores(train_set)
    criteria_scores = res_df[criteria].values.tolist()
    params = optimize_params(criteria_scores, real_scores, eval_function)
    return np.round(params, 2)

# Retorna un dataset con el MSE por grupo
def calculate_mse(result_set, normalize):
    if normalize:
        mse_dict = result_set.groupby('dataset')[result_set.columns.tolist()].apply(lambda x: mean_squared_error(x['real_eval']/3, x['gpt_eval']/3)).to_dict()
        overall_mse = mean_squared_error(result_set['real_eval']/3, result_set['gpt_eval']/3)
    else:
        mse_dict = result_set.groupby('dataset')[result_set.columns.tolist()].apply(lambda x: mean_squared_error(x['real_eval'], x['gpt_eval'])).to_dict()
        overall_mse = mean_squared_error(result_set['real_eval'], result_set['gpt_eval'])

    mse_dict['All'] = overall_mse
    return mse_dict

# Muestra un gráfico con los puntajes obtenidos para cada pregunta ordenadas por puntaje real (0-3)
def show_distribution(full_df):
    rep = full_df['repetition'].nunique()
    full_df = full_df.drop(columns=['params'])

    info_cols = ['row', 'dataset', 'question', 'answer', 'context']
    extra_cols = full_df.columns.difference(['question', 'answer', 'context', 'real_eval', 'row', 'dataset', 'repetition', 'gpt_eval', 'score']).tolist()
    for col in info_cols + extra_cols:
        if full_df[col].dtype == 'object':
            full_df[col] = full_df[col].str.wrap(80).apply(lambda x: x.replace('\n', '<br>'))

    full_df = full_df.pivot(index=['question', 'answer', 'context', 'real_eval', 'row', 'dataset'], columns='repetition', values=['gpt_eval', 'score'] + extra_cols)
    full_df = full_df.sort_values('real_eval').reset_index()
    full_df.loc[full_df['dataset'] == 'C1-OscarBadAnswers20', 'dataset'] = 'C1-BadAnswers'

    value_counts = full_df['real_eval'].value_counts()
    n = np.array([value_counts.get(i, 0) for i in range(4)])
    x_pos = [x + (y+1)/(n[x]+1) for x in range(4) for y in range(n[x])]

    def plot(col, title):
        dev = full_df[col].apply(lambda row: row.std(ddof=0), axis=1).values.tolist()
        mean = full_df[col].apply(lambda row: round(row.mean(), 2), axis=1).values.tolist()

        fig = go.Figure()

        if col == 'gpt_eval':
            for i in range(4):
                fig.add_trace(go.Scatter(
                    x=[i, i + 1],
                    y=[i, i],
                    mode='lines',
                    line=dict(color='red', width=1),
                    showlegend=False,
                    hoverinfo='none'
                ))

        # Información extra
        if rep == 1:
            template_cols = info_cols + [col] + extra_cols
            customdata = list(zip(*[full_df[col] for col in info_cols], mean, *[full_df[col][1] for col in extra_cols]))
        else:
            template_cols = info_cols + [col]
            customdata = list(zip(*[full_df[col] for col in info_cols], mean))

        template = ''
        for i, x in enumerate(template_cols):
            template += f'<b>{x}:</b> %{{customdata[{i}]}}<br>'
        template += '<extra></extra>'

        # Colores por clase (dataset)
        colors = sample_colorscale(px.colors.qualitative.Plotly, [i / 3 for i in range(4)])

        # Añadir los puntos
        for n, cls in enumerate(sorted(full_df['dataset'].unique())):
            indices = full_df.index[full_df['dataset'] == cls].tolist()
            x_filtered = [x_pos[i] for i in indices]
            y_filtered = [mean[i] for i in indices]
            dev_filtered = [dev[i] for i in indices]
            customdata_filtered = [customdata[i] for i in indices]

            # Color barra de error
            color_hex = px.colors.qualitative.Plotly[n]
            r = int(color_hex[1:3], 16)
            g = int(color_hex[3:5], 16)
            b = int(color_hex[5:7], 16)
            alpha = 0.5
            color_rgba = f"rgba({r}, {g}, {b}, {alpha})"

            fig.add_trace(go.Scatter(
                x=x_filtered,
                y=y_filtered,
                mode='markers',
                marker=dict(size=8, color=color_hex),
                error_y=dict(type='data', array=dev_filtered, visible=True, thickness=2, width=4, color=color_rgba),
                customdata=customdata_filtered,
                hovertemplate=template,
                name=cls
            ))

        # Configurar el layout
        y_range = (0, 3) if col == 'gpt_eval' else (0, 10)
        fig.update_layout(
            title=title,
            title_x=0.5,
            xaxis_title='Real Eval',
            yaxis_title='GPT Eval',
            xaxis=dict(tickvals=[0, 1, 2, 3]),
            legend_title_text='Dataset',
            template='plotly_white',
            showlegend=True,
            width=1200,
            height=700,
            hoverlabel=dict(
                bgcolor="green",
                font_size=12
            )
        )

        # Mostrar el gráfico
        fig.show()
        print()

    plot('gpt_eval', 'Distribution of scores obtained by the model')
    #plot('score', 'Distribución de puntajes GPT sin normalizar')

# Exporta las salidas GPT a un archivo EXCEL
def export_responses(response_set, prompt, repetitions, set_size, seed, model, temperature, balance_set, repeat_set):
    dir = "Responses"
    if not os.path.exists(dir):
        os.makedirs(dir)

    timezone = pytz.timezone('America/Santiago')
    date = datetime.now(timezone)
    formatted_date = date.strftime('%Y%m%d-%H%M%S')
    filename = f'{dir}/{formatted_date}.xlsx'

    metadata = {
        'prompt': prompt,
        'repetitions': repetitions,
        'set_size': set_size,
        'seed': seed,
        'model': model,
        'temperature': temperature,
        'repeat_set': repeat_set,
        'balance_set': balance_set
    }
    md_set = pd.DataFrame.from_dict(metadata, orient='index')

    with pd.ExcelWriter(filename) as writer:
        response_set.to_excel(writer, sheet_name='Responses', index=False)
        md_set.to_excel(writer, sheet_name='Metadata', index=True, header=False)
    return filename

# Genera salidas GPT para un conjunto de datos
def generate_responses(dataset, prompts, repetitions, set_size=100, seed=42, model="gpt-4o-mini", temperature=0.1, balance_set=False, repeat_set=False):
    sets = []
    for i in range(repetitions):
        if repeat_set:
            sets.append(generate_set(dataset, set_size, seed, balance=False, exclude_set=None))
        else:
            sets.append(generate_set(dataset, set_size, seed + i, balance=False, exclude_set=None))

    filenames = []
    for i, prompt_data in enumerate(prompts):
        prompt = prompt_data.prompt
        criteria = prompt_data.criteria
        response_set = pd.DataFrame()

        for j in range(repetitions):
            print(f"Generando respuestas para Prompt {i+1} / Conjunto {j+1}")
            rep_set = eval_gpt(sets[j], prompt, criteria, model, temperature)
            rep_set['repetition'] = j+1

            response_set = pd.concat([response_set, rep_set], ignore_index=True)
            print()

        prompt_structure = json.dumps(prompt_data.base_structure())
        filename = export_responses(response_set, prompt_structure, repetitions, set_size, seed, model, temperature, balance_set, repeat_set)
        filenames.append(filename)

# Lee y muestra resultados de un archivo EXCEL
def read_evals(filenames, normalize=False):
    df_mean_all = pd.DataFrame()
    df_std_all = pd.DataFrame()

    for filename in filenames:
        full_df = pd.read_excel(filename, sheet_name='Evaluation')
        md = pd.read_excel(filename, sheet_name='Metadata (res)', header=None, index_col=0).T.reset_index(drop=True)
        df = full_df.copy()
        df = df[['repetition', 'dataset', 'real_eval', 'gpt_eval']]
        df['rounded_gpt_eval'] = round(df['gpt_eval']).astype(int)

        mp_stats = []
        for repetition in df['repetition'].unique():
            df_rep = df[df['repetition'] == repetition]

            # Métricas de regresión
            if normalize:
                micro_mse = mean_squared_error(df_rep['real_eval']/3, df_rep['gpt_eval']/3)
                mse_per_set = df_rep.groupby('dataset')[df_rep.columns.tolist()].apply(lambda x: mean_squared_error(x['real_eval']/3, x['gpt_eval']/3)).to_dict()
                mae = mean_absolute_error(df_rep['real_eval']/3, df_rep['gpt_eval']/3)
            else:
                micro_mse = mean_squared_error(df_rep['real_eval'], df_rep['gpt_eval'])
                mse_per_set = df_rep.groupby('dataset')[df_rep.columns.tolist()].apply(lambda x: mean_squared_error(x['real_eval'], x['gpt_eval'])).to_dict()
                mae = mean_absolute_error(df_rep['real_eval'], df_rep['gpt_eval'])

            mse_per_set = {'mse_' + k: v for k, v in mse_per_set.items()}
            mse_stats = {
                'micro_mse': micro_mse,
            }
            mse_stats.update(mse_per_set)

            # MSE por clase (para calcular el macro)
            mse_per_class = {}
            for cls in sorted(df_rep['real_eval'].unique()):
                y_true = df_rep.loc[df_rep['real_eval'] == cls, 'real_eval']
                y_pred = df_rep.loc[df_rep['real_eval'] == cls, 'gpt_eval']
                if len(y_true) > 0:
                    mse_per_class[cls] = mean_squared_error(y_true, y_pred)

            macro_mse = np.mean(list(mse_per_class.values()))

            spearman, p_value = spearmanr(df_rep['real_eval'], df_rep['gpt_eval'])
            r2 = r2_score(df_rep['real_eval'], df_rep['gpt_eval'])

            # Métricas de clasificación: Se calculan con puntaje GPT redondeado (0-3)
            accuracy = accuracy_score(df_rep['real_eval'], df_rep['rounded_gpt_eval'])
            precision = precision_score(df_rep['real_eval'], df_rep['rounded_gpt_eval'], average='weighted', zero_division=0)
            recall = recall_score(df_rep['real_eval'], df_rep['rounded_gpt_eval'], average='weighted', zero_division=0)
            f1 = f1_score(df_rep['real_eval'], df_rep['rounded_gpt_eval'], average='weighted', zero_division=0)

            stats = {
                'spearman': spearman,
                'macro_mse': macro_mse
            }
            stats.update(mse_stats)
            stats.update({
                'mae': mae,
                'r2': r2,
                'accuracy': accuracy,
                'precision': precision,
                'recall': recall,
                'f1': f1
            })
            mp_stats.append(stats)

        mp_stats = pd.DataFrame(mp_stats)
        df_mean = mp_stats.apply(['mean'])
        df_std = mp_stats.apply([np.std])

        df_mean.insert(0, 'prompt', md['prompt'].iloc[0])
        df_std.insert(0, 'prompt', md['prompt'].iloc[0])
        df_mean_all = pd.concat([df_mean_all, df_mean], ignore_index=True)
        df_std_all = pd.concat([df_std_all, df_std], ignore_index=True)

    pd.set_option('display.max_columns', None)
    pd.set_option('display.max_colwidth', None)

    print("\nTabla Promedios")
    display(df_mean_all)
    print("\nTabla Desviación estándar")
    display(df_std_all)
    pd.reset_option('^display.', silent=True)

    repeat_test_set = md['repeat_set'].iloc[0]
    repetitions = md['repetitions'].iloc[0]
    if len(filenames) == 1 and (repeat_test_set or repetitions == 1):
        print()
        show_distribution(full_df)

# Exportar archivo de evaluaciones
def export_eval(filename, eval_set, res_md, eval_function, eval_params, train_set_size, seed, model, temperature):
    dir = "Evals"
    if not os.path.exists(dir):
        os.makedirs(dir)

    timezone = pytz.timezone('America/Santiago')
    date = datetime.now(timezone)
    formatted_date = date.strftime('%Y%m%d-%H%M%S')

    filename = os.path.splitext(os.path.basename(filename))[0]

    if eval_params is None:
        filename = f'{dir}/T_{filename}_eval.xlsx'
    else:
        filename = f'{dir}/{filename}_eval.xlsx'

    eval_md = {
        'eval_function': eval_function,
        'eval_params': eval_params,
        'train_set_size': train_set_size,
        'seed': seed,
        'model': model,
        'temperature': temperature
    }
    eval_md = pd.DataFrame.from_dict(eval_md, orient='index')

    with pd.ExcelWriter(filename) as writer:
        eval_set.to_excel(writer, sheet_name='Evaluation', index=False)
        eval_md.to_excel(writer, sheet_name='Metadata (eval)', index=True, header=False)
        res_md.to_excel(writer, sheet_name='Metadata (res)', index=True, header=False)
    return filename

# Evalúa en base a las salidas de GPT
def evaluate(filename, dataset, eval_function, eval_params=None, train_set_size=100, seed=42, model="gpt-4o-mini", temperature=0.1, prompt_folder="GPTEvaluator/Experiments/Miniprompts_v2"):
    res_df = pd.read_excel(filename, sheet_name='Responses')

    res_md = pd.read_excel(filename, sheet_name='Metadata', header=None, index_col=0)
    prompt_dict = json.loads(res_md.T.reset_index(drop=True)['prompt'][0])
    prompt = generate_prompts(prompt_dict, prompt_folder, visualize=False)[0]

    # Dataset final de evaluaciones
    eval_set = pd.DataFrame()

    for repetition in res_df['repetition'].unique():
        rep_df = res_df[res_df['repetition'] == repetition]
        test_set = rep_df[rep_df['row'].isin(dataset['row'])].copy()

        # ENTRENAMIENTO
        rep_params = eval_params
        if eval_params is None:
            print(f"Evaluando conjunto de prueba {repetition} con AJUSTE")
            train_set = generate_set(dataset, train_set_size, int(seed + repetition), balance=False, exclude_set=test_set)
            rep_params = train(train_set, prompt.prompt, prompt.criteria, eval_function, model, temperature)
            str_params = "[" + ", ".join("{:.2f}".format(param) for param in rep_params) + "]"
            print()
            print(f"Parámetros obtenidos: {str_params}")

        real_scores = rep_df['real_eval'].tolist()
        criteria_scores = rep_df[prompt.criteria].values.tolist()

        pred_scores = convert_gpt_scores(criteria_scores, real_scores, eval_function, rep_params)
        test_set['gpt_eval'] = pred_scores
        test_set['params'] = ", ".join("{:.2f}".format(param) for param in rep_params)

        eval_set = pd.concat([eval_set, test_set], ignore_index=True)

    if eval_params is None: print()
    return export_eval(filename, eval_set, res_md, eval_function, eval_params, train_set_size, seed, model, temperature)

def evaluate_mul(filenames, dataset, eval_function, eval_params=None, train_set_size=100, seed=42, model="gpt-4o-mini", temperature=0.1, prompt_folder="GPTEvaluator/Experiments/Miniprompts_v2"):
    eval_files = []
    for filename in filenames:
        print(f"EVALUANDO {filename}")
        eval_file = evaluate(filename, dataset, eval_function, eval_params, train_set_size, seed, model, temperature, prompt_folder)
        eval_files.append(eval_file)

    if len(eval_files) > 0:
        read_evals(eval_files)

# Espacio para experimentos

In [ ]:
column_data = {
    "context": "Contexto simple",
    "question": "Pregunta",
    "answer": "Respuesta",
    "real_eval": "Promedio Redondeado",
    "dataset": "DataSet"
}

df = load_dataset("datasets_v2.xlsx", "AllDatasets (1dif)", column_data)

,context,question,answer,real_eval,dataset,row
0,BFS es preferible en problemas que requieren e...,¿En qué tipo de problemas una búsqueda BFS pod...,El bfs es mucho mas util en ejecuciones cortas...,2,C3-Sample100,2
1,BFS es preferible en problemas que requieren e...,¿En qué tipo de problemas una búsqueda BFS pod...,en una situación de resolución de un problema ...,2,C3-Sample100,3
2,BFS es preferible en problemas que requieren e...,¿En qué tipo de problemas una búsqueda BFS pod...,en problemas donde pidan obtener el camino de ...,3,C3-Sample100,4
3,BFS es preferible en problemas que requieren e...,¿En qué tipo de problemas una búsqueda BFS pod...,en problemas de grafos no ponderados ya que no...,3,C3-Sample100,5
4,"BFS explora nodos nivel por nivel, visitando p...",¿Cuál es la principal diferencia entre búsqued...,La búsqueda por anchura tiene un procedimiento...,3,C3-Sample100,6

real_eval
3    127
2     75
0     52
1     36
Name: count, dtype: int64

dataset
C2-Nan                  92
C3-Sample100            91
C2-Sample100            90
C1-OscarBadAnswers20    17
Name: count, dtype: int64

In [ ]:
prompt_data = {
    "context": "context.txt",
    "examples_basic": "examples_4G4B_basic.txt",
    "question": "question.txt",
    "answer": "answer.txt",
    "instructions": {
        "score": "score_single.txt",
        "feedback": "*"
    }
}

prompt_folder = "GPTEvaluator/Experiments/Miniprompts_v2"

prompts = generate_prompts(prompt_data, prompt_folder)

**Knowledge:** {Context}

### Examples
**Question**: ¿Cuando se recomienda utilizar arreglos en vez de listas enlazadas? Haga referencia a complejidades temporales en su explicación.
**Student's Answer**: Se recomienta utilizar arreglos cuando se quiere acceder a elementos en posiciones específicas. Acceder a posiciones en un arreglo tiene complejidad temporal O(1), mientras que en una lista enlazada la complejidad es O(n).
**Score**: 10

**Question**: ¿Cuál es la complejidad temporal del peor caso para la operación de búsqueda en una tabla hash y por qué? Describe las condiciones que debe tener la tabla para encontrarse en este peor caso.
**Student's Answer**: La complejidad del peor caso es O(n). Esta puede ocurrir cuando todos los datos de la tabla se encuentran contiguos en el arreglo, y cuando se busca una clave, esta búsqueda hace colisión con todos los datos que estaban almacenados.
**Score**: 10

**Question**: ¿Cómo se podría implementar un historial de navegación web usando dos pilas? El historial debe permitir ir hacia atrás y adelante con las páginas previamente visitadas. Describa un algoritmo.
**Student's Answer**: En una pila se almacenan las páginas visitadas (pila atrás) y la otra se mantiene vacía (pila adelante). Al volver hacia atrás, se saca una página de atrás y se coloca en la pila adelante. Al ir hacia adelante, se saca una página de adelante y se coloca en la pila atrás.
**Score**: 10

**Question**: ¿Por qué el acceso a una posición específica en un arreglo es O(1), es decir, no depende de la cantidad de datos?
**Student's Answer**: Para acceder a una posición k en un arreglo basta con acceder a la posición que se obtiene de sumar al puntero que apunta al primer elemento una cantidad de bytes igual a k*sizeof(elem). Sumar punteros y acceder a la posición es O(1).
**Score**: 10

**Question**: ¿Cuando se recomienda utilizar arreglos en vez de listas enlazadas? Haga referencia a complejidades temporales en su explicación.
**Student's Answer**: Un arreglo es recomendable en determinadas situaciones, mientras que la lista enlazada en otras.
**Score**: 0

**Question**: ¿Cuál es la complejidad temporal del peor caso para la operación de búsqueda en una tabla hash y por qué? Describe las condiciones que debe tener la tabla para encontrarse en este peor caso.
**Student's Answer**: La complejidad del peor caso es ocurre cuando la tabla es inefectiva para realizar las operación de búsqueda.
**Score**: 0

**Question**: ¿Cómo se podría implementar un historial de navegación web usando dos pilas? El historial debe permitir ir hacia atrás y adelante con las páginas previamente visitadas. Describa un algoritmo.
**Student's Answer**: Usamos dos pilas para ir hacia adelante y hacia atrás en el historial.
**Score**: 0

**Question**: ¿Por qué el acceso a una posición específica en un arreglo es O(1), es decir, no depende de la cantidad de datos?
**Student's Answer**: El acceso es O(1) por que toma un tiempo constante y no depende de la cantidad de datos.
**Score**: 0

**Question:** {Question}

**Student's Answer:** {Answer}

Instructions:
(score) Assign a score between 0 and 10 to the student's answer.

{feedback}

I expect a dict in python as answer: {{"score": 'score'}}

Python dict:


Archivos a utilizar (4):

feedback_full.txt
feedback_full_soft.txt
feedback_minimal.txt
feedback_normal.txt

In [ ]:
generate_responses(df, prompts, repetitions=10, set_size=100, seed=42, model="gpt-4o-mini-2024-07-18", temperature=0.1, balance_set=False, repeat_set=False)

Generando respuestas para Prompt 1 / Conjunto 1
41-29-5-14-49-39-43-47-21-44-37-28-13-17-6-26-22-33-25-9-19-7-32-10-45-40-48-12-35-30-0-18-20-3-4-31-16-42-1-11-34-23-24-8-36-27-2-46-38-15-59-50-80-63-70-56-57-52-62-58-72-60-69-61-74-77-76-75-78-54-82-96-53-55-68-71-88-79-73-90-93-99-51-85-81-66-98-92-67-84-91-87-65-83-94-97-95-89-86-64-
Generando respuestas para Prompt 1 / Conjunto 2
47-30-28-17-5-26-7-13-14-45-6-10-49-33-9-34-32-37-35-11-8-43-42-31-38-40-41-46-2-39-22-24-29-21-0-12-3-4-25-20-44-1-48-27-16-36-19-18-15-23-66-56-51-58-71-67-55-61-57-53-77-72-64-89-75-79-54-68-87-69-81-50-91-60-59-76-90-63-62-70-65-93-86-94-83-95-97-82-80-74-88-84-52-85-73-92-78-98-99-96-
Generando respuestas para Prompt 1 / Conjunto 3
10-2-12-26-19-47-30-4-15-25-5-1-35-22-11-36-16-8-20-32-38-3-21-40-43-23-6-29-18-44-39-14-37-13-17-24-42-49-46-41-28-7-45-0-27-9-31-33-48-34-56-52-57-53-50-61-66-83-78-73-55-51-54-68-91-63-60-79-59-80-85-87-76-72-58-71-74-97-77-82-88-75-86-98-93-65-84-81-69-92-94-64-99-62-95-89-90-67-96-70-
Generando respuestas para Prompt 1 / Conjunto 4
25-38-26-14-4-23-40-15-16-18-8-21-17-24-28-37-22-5-1-39-10-6-43-45-20-31-47-19-7-27-13-33-44-41-42-46-12-11-36-48-49-30-2-3-9-0-34-35-29-56-58-57-50-51-76-63-54-62-32-78-70-86-52-82-59-68-89-61-85-66-90-53-91-84-67-65-75-77-72-69-87-83-64-79-73-80-88-55-92-94-98-93-60-95-74-81-71-96-99-97-
Generando respuestas para Prompt 1 / Conjunto 5
17-16-

ERROR:openai_multi_client:Error processing Payload(endpoint='chats', data={'model': 'gpt-4o-mini-2024-07-18', 'temperature': 0.1, 'n': 1, 'timeout': 10, 'messages': [{'role': 'user', 'content': '**Knowledge:** Modela usuarios como nodos y conexiones como aristas. Usa BFS para explorar desde A, nivel por nivel, hasta encontrar B, contando los niveles como el grado de separación. Retorna el nivel en que se encuentra B.\n\n### Examples\n**Question**: ¿Cuando se recomienda utilizar arreglos en vez de listas enlazadas? Haga referencia a complejidades temporales en su explicación.\n**Student\'s Answer**: Se recomienta utilizar arreglos cuando se quiere acceder a elementos en posiciones específicas. Acceder a posiciones en un arreglo tiene complejidad temporal O(1), mientras que en una lista enlazada la complejidad es O(n).\n**Score**: 10\n\n**Question**: ¿Cuál es la complejidad temporal del peor caso para la operación de búsqueda en una tabla hash y por qué? Describe las condiciones que debe tener la tabla para encontrarse en este peor caso.\n**Student\'s Answer**: La complejidad del peor caso es O(n). Esta puede ocurrir cuando todos los datos de la tabla se encuentran contiguos en el arreglo, y cuando se busca una clave, esta búsqueda hace colisión con todos los datos que estaban almacenados.\n**Score**: 10\n\n**Question**: ¿Cómo se podría implementar un historial de navegación web usando dos pilas? El historial debe permitir ir hacia atrás y adelante con las páginas previamente visitadas. Describa un algoritmo.\n**Student\'s Answer**: En una pila se almacenan las páginas visitadas (pila atrás) y la otra se mantiene vacía (pila adelante). Al volver hacia atrás, se saca una página de atrás y se coloca en la pila adelante. Al ir hacia adelante, se saca una página de adelante y se coloca en la pila atrás.\n**Score**: 10\n\n**Question**: ¿Por qué el acceso a una posición específica en un arreglo es O(1), es decir, no depende de la cantidad de datos?\n**Student\'s Answer**: Para acceder a una posición k en un arreglo basta con acceder a la posición que se obtiene de sumar al puntero que apunta al primer elemento una cantidad de bytes igual a k*sizeof(elem). Sumar punteros y acceder a la posición es O(1).\n**Score**: 10\n\n**Question**: ¿Cuando se recomienda utilizar arreglos en vez de listas enlazadas? Haga referencia a complejidades temporales en su explicación.\n**Student\'s Answer**: Un arreglo es recomendable en determinadas situaciones, mientras que la lista enlazada en otras.\n**Score**: 0\n\n**Question**: ¿Cuál es la complejidad temporal del peor caso para la operación de búsqueda en una tabla hash y por qué? Describe las condiciones que debe tener la tabla para encontrarse en este peor caso.\n**Student\'s Answer**: La complejidad del peor caso es ocurre cuando la tabla es inefectiva para realizar las operación de búsqueda.\n**Score**: 0\n\n**Question**: ¿Cómo se podría implementar un historial de navegación web usando dos pilas? El historial debe permitir ir hacia atrás y adelante con las páginas previamente visitadas. Describa un algoritmo.\n**Student\'s Answer**: Usamos dos pilas para ir hacia adelante y hacia atrás en el historial.\n**Score**: 0\n\n**Question**: ¿Por qué el acceso a una posición específica en un arreglo es O(1), es decir, no depende de la cantidad de datos?\n**Student\'s Answer**: El acceso es O(1) por que toma un tiempo constante y no depende de la cantidad de datos.\n**Score**: 0\n\n**Question:** En el contexto de redes sociales, ¿cómo podría usar BFS para encontrar el grado de separación entre dos personas (A y B)? El grado de separación mide la distancia más corta entre dos usuarios, considerando a los usuarios como nodos y las conexiones como followers o following.\n\n**Student\'s Answer:** Para usar BFS para encontrar el grado de separación entre dos personas A y B, puedo utilizar un contador en el cual, con cada iteración de búsqueda donde se pase por una conexión, se aumente uno al contador. De ese modo. al encontrar el camino más corto entre de los nodos correspondientes a la persona A con la persona B, tendré una distancia que corresponde también a la cantidad de separaciones, por conexiones.\n\nInstructions:\n(score) Assign a score between 0 and 10 to the student\'s answer.\n\n(feedback)\nProvide feedback to the "Student\'s Answer".\nStart by stating whether the answer is good/excelent or poor/insatisfactory.\nIf the answer is good/excelent, affirm the student\'s understanding and potentially add a brief note on why their response was particularly effective or comprehensive.\nIf the answer is poor/insatisfactory, clearly identify the inaccuracies or errors. Provide specific suggestions on how to improve, ensuring the feedback is constructive.\nWithin 150 words.\n\nI expect a dict in python as answer: {"score": \'score\', "feedback": \'feedback\'}\n\nPython dict:'}]}, metadata={'index': 29}, max_retries=3, retry_multiplier=1, retry_max=10, attempt=1, failed=False, response=None, callback=None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/openai/api_requestor.py", line 755, in _interpret_response_line
    data = json.loads(rbody)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 356, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/openai_multi_client/__init__.py", line 111, in _worker
    payload = await self._process_payload(payload)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/openai_multi_client/__init__.py", line 81, in _process_payload
    payload.response = await openai.ChatCompletion.acreate(**payload.data)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/openai/api_resources/chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/openai/api_resources/abstract/engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/openai/api_requestor.py", line 382, in arequest
    resp, got_stream = await self._interpret_async_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/openai/api_requestor.py", line 728, in _interpret_async_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.12/dist-packages/openai/api_requestor.py", line 757, in _interpret_response_line
    raise error.APIError(
openai.error.APIError: HTTP code 520 from API (<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>


<title>api.openai.com | 520: Web server is returning an unknown error</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" />


</head>
<body>
<div id="cf-wrapper">
    <div id="cf-error-details" class="p-0">
        <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8">
            <h1 class="inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2">
              <span class="inline-block">Web server is returning an unknown error</span>
              <span class="code-label">Error code 520</span>
            </h1>
            <div>
               Visit <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_520&utm_campaign=api.openai.com" target="_blank" rel="noopener noreferrer">cloudflare.com</a> for more information.
            </div>
            <div class="mt-3">2025-10-05 02:53:46 UTC</div>
        </header>
        <div class="my-8 bg-gradient-gray">
            <div class="w-240 lg:w-full mx-auto">
                <div class="clearfix md:px-8">

<div id="cf-browser-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">

    <span class="cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>

  </div>
  <span class="md:block w-full truncate">You</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">

    Browser

  </h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-cloudflare-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_520&utm_campaign=api.openai.com" target="_blank" rel="noopener noreferrer">
    <span class="cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
    </a>
  </div>
  <span class="md:block w-full truncate">Chicago</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">
    <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_520&utm_campaign=api.openai.com" target="_blank" rel="noopener noreferrer">
    Cloudflare
    </a>
  </h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-host-status" class="cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">

    <span class="cf-icon-server block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>

  </div>
  <span class="md:block w-full truncate">api.openai.com</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">

    Host

  </h3>
  <span class="leading-1.3 text-2xl text-red-error">Error</span>
</div>

                </div>
            </div>
        </div>

        <div class="w-240 lg:w-full mx-auto mb-8 lg:px-8">
            <div class="clearfix">
                <div class="w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What happened?</h2>
                    <p>There is an unknown connection issue between Cloudflare and the origin web server. As a result, the web page can not be displayed.</p>
                </div>
                <div class="w-1/2 md:w-full float-left leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What can I do?</h2>
                          <h3 class="text-15 font-semibold mb-2">If you are a visitor of this website:</h3>
      <p class="mb-6">Please try again in a few minutes.</p>

      <h3 class="text-15 font-semibold mb-2">If you are the owner of this website:</h3>
      <p><span>There is an issue between Cloudflare's cache and your origin web server. Cloudflare monitors for these errors and automatically investigates the cause. To help support the investigation, you can pull the corresponding error log from your web server and submit it our support team.  Please include the Ray ID (which is at the bottom of this error page).</span> <a rel="noopener noreferrer" href="https://developers.cloudflare.com/support/troubleshooting/http-status-codes/cloudflare-5xx-errors/error-520/">Additional troubleshooting resources</a>.</p>
                </div>
            </div>
        </div>

        <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">9899a15be9053426</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
      Your IP:
      <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>
      <span class="hidden" id="cf-footer-ip">34.41.218.97</span>
      <span class="cf-footer-separator sm:hidden">&bull;</span>
    </span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_520&utm_campaign=api.openai.com" id="brand_link" target="_blank">Cloudflare</a></span>

  </p>
  <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
</div><!-- /.error-footer -->


    </div>
</div>
</body>
</html>
)
ERROR:openai_multi_client:Error processing Payload(endpoint='chats', data={'model': 'gpt-4o-mini-2024-07-18', 'temperature': 0.1, 'n': 1, 'timeout': 10, 'messages': [{'role': 'user', 'content': '**Knowledge:** Sube desde el nodo actual hacia la raíz hasta encontrar un nodo que sea el hijo izquierdo de su padre. Ese padre será el sucesor.\n\n### Examples\n**Question**: ¿Cuando se recomienda utilizar arreglos en vez de listas enlazadas? Haga referencia a complejidades temporales en su explicación.\n**Student\'s Answer**: Se recomienta utilizar arreglos cuando se quiere acceder a elementos en posiciones específicas. Acceder a posiciones en un arreglo tiene complejidad temporal O(1), mientras que en una lista enlazada la complejidad es O(n).\n**Score**: 10\n\n**Question**: ¿Cuál es la complejidad temporal del peor caso para la operación de búsqueda en una tabla hash y por qué? Describe las condiciones que debe tener la tabla para encontrarse en este peor caso.\n**Student\'s Answer**: La complejidad del peor caso es O(n). Esta puede ocurrir cuando todos los datos de la tabla se encuentran contiguos en el arreglo, y cuando se busca una clave, esta búsqueda hace colisión con todos los datos que estaban almacenados.\n**Score**: 10\n\n**Question**: ¿Cómo se podría implementar un historial de navegación web usando dos pilas? El historial debe permitir ir hacia atrás y adelante con las páginas previamente visitadas. Describa un algoritmo.\n**Student\'s Answer**: En una pila se almacenan las páginas visitadas (pila atrás) y la otra se mantiene vacía (pila adelante). Al volver hacia atrás, se saca una página de atrás y se coloca en la pila adelante. Al ir hacia adelante, se saca una página de adelante y se coloca en la pila atrás.\n**Score**: 10\n\n**Question**: ¿Por qué el acceso a una posición específica en un arreglo es O(1), es decir, no depende de la cantidad de datos?\n**Student\'s Answer**: Para acceder a una posición k en un arreglo basta con acceder a la posición que se obtiene de sumar al puntero que apunta al primer elemento una cantidad de bytes igual a k*sizeof(elem). Sumar punteros y acceder a la posición es O(1).\n**Score**: 10\n\n**Question**: ¿Cuando se recomienda utilizar arreglos en vez de listas enlazadas? Haga referencia a complejidades temporales en su explicación.\n**Student\'s Answer**: Un arreglo es recomendable en determinadas situaciones, mientras que la lista enlazada en otras.\n**Score**: 0\n\n**Question**: ¿Cuál es la complejidad temporal del peor caso para la operación de búsqueda en una tabla hash y por qué? Describe las condiciones que debe tener la tabla para encontrarse en este peor caso.\n**Student\'s Answer**: La complejidad del peor caso es ocurre cuando la tabla es inefectiva para realizar las operación de búsqueda.\n**Score**: 0\n\n**Question**: ¿Cómo se podría implementar un historial de navegación web usando dos pilas? El historial debe permitir ir hacia atrás y adelante con las páginas previamente visitadas. Describa un algoritmo.\n**Student\'s Answer**: Usamos dos pilas para ir hacia adelante y hacia atrás en el historial.\n**Score**: 0\n\n**Question**: ¿Por qué el acceso a una posición específica en un arreglo es O(1), es decir, no depende de la cantidad de datos?\n**Student\'s Answer**: El acceso es O(1) por que toma un tiempo constante y no depende de la cantidad de datos.\n**Score**: 0\n\n**Question:** Explique en palabras y paso a paso cómo encontrar el nodo sucesor o siguiente al \'actual\' en un árbol binario de búsqueda. Considere que el nodo actual no tiene hijos.\n\n**Student\'s Answer:** Para encontrar el sucesor del nodo actual, se debe recorrer el arbol binario por los sub-arboles izquierdos y/o derechos, dependiendo del valor a buscar, hasta encontrar el nodo que contenga el valor menor, pero que sea mayor al buscado.\n\nInstructions:\n(score) Assign a score between 0 and 10 to the student\'s answer.\n\n(feedback)\nProvide feedback to the "Student\'s Answer".\nStart by stating whether the answer is good/excelent or poor/insatisfactory.\nIf the answer is good/excelent, affirm the student\'s understanding and potentially add a brief note on why their response was particularly effective or comprehensive.\nIf the answer is poor/insatisfactory, clearly identify the inaccuracies or errors. Provide specific suggestions on how to improve, ensuring the feedback is constructive.\nWithin 150 words.\n\nI expect a dict in python as answer: {"score": \'score\', "feedback": \'feedback\'}\n\nPython dict:'}]}, metadata={'index': 4}, max_retries=3, retry_multiplier=1, retry_max=10, attempt=1, failed=False, response=None, callback=None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/openai/api_requestor.py", line 755, in _interpret_response_line
    data = json.loads(rbody)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 356, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

5-1-35-3-44-2-38-33-45-25-26-42-48-39-0-24-47-8-46-6-30-27-14-19-7-49-23-43-31-32-28-40-36-34-22-41-10-13-15-9-18-12-21-20-11-37-50-51-62-29-68-59-53-56-64-57-70-60-76-84-67-82-80-55-65-79-61-88-78-4-69-75-71-73-58-72-89-86-54-97-77-93-91-66-81-74-85-52-96-95-87-92-94-98-90-83-63-99-
Generando respuestas para Prompt 1 / Conjunto 6
34-8-2-15-44-3-28-26-17-16-47-31-27-9-0-25-11-24-4-39-21-22-38-7-18-43-45-33-23-32-14-30-12-42-48-10-6-37-36-35-1-29-41-20-5-49-13-40-19-51-76-53-50-71-67-72-75-52-69-59-55-73-60-86-79-90-83-65-78-85-63-88-57-62-61-64-77-70-58-80-81-56-91-84-93-66-96-82-89-46-95-74-92-87-97-98-99-68-54-94-
Generando respuestas para Prompt 1 / Conjunto 7
1-11-40-46-42-17-45-2-23-33-16-18-38-21-26-9-19-7-0-8-20-29-22-15-3-12-10-35-13-25-4-34-31-6-24-27-49-36-44-32-47-5-43-30-14-41-58-71-62-57-68-54-76-28-80-67-65-63-55-82-81-51-64-72-86-53-70-77-84-90-56-89-37-87-50-92-78-93-88-60-48-59-91-75-95-85-73-94-61-39-66-69-83-97-52-96-79-74-99-98-
Generando respuestas para Prompt 1 / Conjunto 8
3-37-6-16-5-26-44-33-24-9-42-27-31-19-18-20-34-22-17-4-29-25-21-46-11-39-23-49-14-1-30-38-0-2-7-12-15-43-28-40-32-35-48-41-36-47-45-57-58-56-71-50-65-63-67-53-62-69-64-77-68-82-13-59-61-85-76-60-8-70-92-10-51-54-55-52-90-80-74-73-89-86-79-87-83-96-88-84-93-94-75-95-91-72-81-97-99-98-66-78-
Generando respuestas para Prompt 1 / Conjunto 9

ERROR:openai_multi_client:Error processing Payload(endpoint='chats', data={'model': 'gpt-4o-mini-2024-07-18', 'temperature': 0.1, 'n': 1, 'timeout': 10, 'messages': [{'role': 'user', 'content': '**Knowledge:** Tener nodos con múltiples claves en árboles B/B+ permite almacenar más información en cada nodo, reduciendo la altura del árbol y mejorando la eficiencia en las operaciones.\n\n### Examples\n**Question**: ¿Cuando se recomienda utilizar arreglos en vez de listas enlazadas? Haga referencia a complejidades temporales en su explicación.\n**Student\'s Answer**: Se recomienta utilizar arreglos cuando se quiere acceder a elementos en posiciones específicas. Acceder a posiciones en un arreglo tiene complejidad temporal O(1), mientras que en una lista enlazada la complejidad es O(n).\n**Score**: 10\n\n**Question**: ¿Cuál es la complejidad temporal del peor caso para la operación de búsqueda en una tabla hash y por qué? Describe las condiciones que debe tener la tabla para encontrarse en este peor caso.\n**Student\'s Answer**: La complejidad del peor caso es O(n). Esta puede ocurrir cuando todos los datos de la tabla se encuentran contiguos en el arreglo, y cuando se busca una clave, esta búsqueda hace colisión con todos los datos que estaban almacenados.\n**Score**: 10\n\n**Question**: ¿Cómo se podría implementar un historial de navegación web usando dos pilas? El historial debe permitir ir hacia atrás y adelante con las páginas previamente visitadas. Describa un algoritmo.\n**Student\'s Answer**: En una pila se almacenan las páginas visitadas (pila atrás) y la otra se mantiene vacía (pila adelante). Al volver hacia atrás, se saca una página de atrás y se coloca en la pila adelante. Al ir hacia adelante, se saca una página de adelante y se coloca en la pila atrás.\n**Score**: 10\n\n**Question**: ¿Por qué el acceso a una posición específica en un arreglo es O(1), es decir, no depende de la cantidad de datos?\n**Student\'s Answer**: Para acceder a una posición k en un arreglo basta con acceder a la posición que se obtiene de sumar al puntero que apunta al primer elemento una cantidad de bytes igual a k*sizeof(elem). Sumar punteros y acceder a la posición es O(1).\n**Score**: 10\n\n**Question**: ¿Cuando se recomienda utilizar arreglos en vez de listas enlazadas? Haga referencia a complejidades temporales en su explicación.\n**Student\'s Answer**: Un arreglo es recomendable en determinadas situaciones, mientras que la lista enlazada en otras.\n**Score**: 0\n\n**Question**: ¿Cuál es la complejidad temporal del peor caso para la operación de búsqueda en una tabla hash y por qué? Describe las condiciones que debe tener la tabla para encontrarse en este peor caso.\n**Student\'s Answer**: La complejidad del peor caso es ocurre cuando la tabla es inefectiva para realizar las operación de búsqueda.\n**Score**: 0\n\n**Question**: ¿Cómo se podría implementar un historial de navegación web usando dos pilas? El historial debe permitir ir hacia atrás y adelante con las páginas previamente visitadas. Describa un algoritmo.\n**Student\'s Answer**: Usamos dos pilas para ir hacia adelante y hacia atrás en el historial.\n**Score**: 0\n\n**Question**: ¿Por qué el acceso a una posición específica en un arreglo es O(1), es decir, no depende de la cantidad de datos?\n**Student\'s Answer**: El acceso es O(1) por que toma un tiempo constante y no depende de la cantidad de datos.\n**Score**: 0\n\n**Question:** ¿Cuál es e la utilidad de tener nodos con múltiples claves en árboles B/B+? Explique.\n\n**Student\'s Answer:** El tener nodos con múltiples claves en árboles B/B+ garantiza una mayor eficiencia, pues al ser árboles autobalanceables (gracias a sus divisiones y fusiones) asegura que su altura se mantendrá mínima, lo cual hace que sus operaciones de búsqueda, inserción y eliminación sean menos costosas lo que implica una complejidad temporal de O(log n).\n\nInstructions:\n(score) Assign a score between 0 and 10 to the student\'s answer.\n\n(feedback)\nProvide feedback to the "Student\'s Answer".\nStart by stating whether the answer is good/excelent or poor/insatisfactory.\nIf the answer is good/excelent, affirm the student\'s understanding and potentially add a brief note on why their response was particularly effective or comprehensive.\nIf the answer is poor/insatisfactory, clearly identify the inaccuracies or errors. Provide specific suggestions on how to improve, ensuring the feedback is constructive.\nWithin 150 words.\n\nI expect a dict in python as answer: {"score": \'score\', "feedback": \'feedback\'}\n\nPython dict:'}]}, metadata={'index': 44}, max_retries=3, retry_multiplier=1, retry_max=10, attempt=1, failed=False, response=None, callback=None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/openai/api_requestor.py", line 755, in _interpret_response_line
    data = json.loads(rbody)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 356, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/openai_multi_client/__init__.py", line 111, in _worker
    payload = await self._process_payload(payload)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/openai_multi_client/__init__.py", line 81, in _process_payload
    payload.response = await openai.ChatCompletion.acreate(**payload.data)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/openai/api_resources/chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/openai/api_resources/abstract/engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/openai/api_requestor.py", line 382, in arequest
    resp, got_stream = await self._interpret_async_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/openai/api_requestor.py", line 728, in _interpret_async_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.12/dist-packages/openai/api_requestor.py", line 757, in _interpret_response_line
    raise error.APIError(
openai.error.APIError: HTTP code 502 from API (<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
)

35-1-46-8-2-17-39-24-40-6-15-5-9-20-28-43-0-41-10-36-47-45-23-16-33-19-22-30-21-4-18-42-13-49-14-32-31-34-37-48-12-29-38-11-26-3-25-51-50-79-73-77-52-66-55-59-63-53-76-78-54-57-64-60-67-71-61-83-80-70-56-27-86-88-7-65-89-74-84-62-72-68-44-93-87-92-94-82-90-91-97-69-75-85-98-96-99-81-58-95-
Generando respuestas para Prompt 1 / Conjunto 10
37-21-2-14-8-45-5-28-36-1-44-25-34-47-24-12-6-15-42-7-4-49-18-30-23-29-13-41-20-9-35-11-0-43-17-33-38-16-31-22-32-27-46-40-39-19-3-10-57-70-50-59-58-52-68-53-76-65-67-72-63-69-54-82-55-75-81-60-77-61-79-64-80-62-66-71-85-96-83-84-78-56-73-74-87-90-86-94-95-88-48-93-89-26-98-91-92-51-99-97-
Generando respuestas para Prompt 2 / Conjunto 1
14-29-49-7-24-13-25-22-35-44-27-1-37-21-6-39-17-9-42-38-46-8-48-16-5-2-33-18-28-45-43-12-23-40-4-15-10-30-20-31-0-26-36-11-3-34-19-32-41-50-47-80-59-63-51-66-56-69-61-52-60-79-72-85-70-57-58-71-91-62-75-78-68-88-64-77-76-65-82-89-73-87-67-95-86-53-81-92-84-74-96-54-98-97-94-93-90-99-83-55-
Generando respuestas para Prompt 2 / Conjunto 2
28-45-23-5-39-43-30-34-47-33-1-44-2-20-3-10-29-7-11-48-24-21-0-12-17-38-37-35-13-36-14-26-49-8-9-6-42-40-27-46-22-18-19-4-41-32-16-15-25-31-50-88-51-56-64-67-66-62-52-79-57-72-89-77-60-71-81-55-73-53-59-92-76-78-85-68-65-87-61-58-86-82-75-80-97-83-94-63-95-70-91-74-98-93-54-99-90-84-96-69-
Generando respuestas para Prompt 2 / Conjunto 3
27-12-10-2-30-19-26-11-36-32-17-23-5-47-45-7-28-35-43-9-13-4-29-0-20-38-14-16-41-22-46-37-1-48-15-8-24-25-6-49-39-40-3-44-21-42-34-31-58-33-64-56-50-66-57-53-51-61-54-87-74-76-91-62-83-89-52-93-79-60-70-73-63-78-81-86-80-18-55-75-71-88-92-59-84-85-98-72-77-82-90-69-94-96-95-65-67-97-68-99-
Generando respuestas para Prompt 2 / Conjunto 4
34-0-42-46-22-31-49-12-20-2-10-24-18-16-14-25-6-36-37-17-35-9-28-27-29-4-13-8-23-26-32-19-1-41-38-3-30-7-48-44-47-43-15-40-39-5-33-21-45-11-50-60-61-71-74-51-56-63-82-53-57-58-70-86-66-65-62-54-68-91-99-83-78-55-76-98-73-69-52-64-67-84-79-77-59-90-75-89-92-72-97-93-95-94-87-85-96-88-81-80-
Generando respuestas para Prompt 2 / Conjunto 5
18-20-40-16-17-1-39-34-10-11-5-8-35-44-33-24-2-0-4-9-29-26-46-25-22-14-28-6-36-13-41-32-47-21-23-45-15-43-7-3-38-37-12-27-30-42-31-49-48-19-52-77-53-85-51-55-60-58-88-68-54-62-61-83-59-56-50-57-64-67-86-73-72-80-79-76-93-69-96-87-71-63-78-91-81-65-89-75-84-74-90-95-97-98-92-82-94-99-66-70-
Generando respuestas para Prompt 2 / Conjunto 6
38-34-2-15-8-3-47-41-44-17-9-27-12-11-14-1-36-46-24-21-23-35-45-16-30-49-7-5-26-28-18-33-6-0-25-31-22-13-43-32-39-10-4-29-48-42-37-40-20-68-19-50-51-62-69-76-82-72-53-63-94-61-54-71-74-86-75-56-52-67-65-79-73-95-64-83-55-81-92-91-85-90-78-80-93-89-70-59-96-58-57-88-77-66-98-60-97-87-99-84-
Generando respuestas para Prompt 2 / Conjunto 7
47-48-39-18-37-28-1-40-46-23-5-22-3-12-11-42-4-43-2-15-33-7-25-20-49-0-17-16-45-13-10-21-35-14-9-30-6-8-36-29-27-26-19-34-31-32-52-44-24-38-41-53-63-55-71-72-54-76-59-51-56-82-98-79-80-70-81-57-65-93-64-69-60-50-84-67-86-62-75-74-61-88-58-68-95-92-89-73-91-78-87-66-97-83-96-90-77-94-85-99-
Generando respuestas para Prompt 2 / Conjunto 8
13-36-47-16-42-6-7-33-1-10-21-2-44-37-32-18-34-14-27-24-41-20-12-8-9-31-26-45-0-11-22-3-23-17-35-5-38-28-43-49-30-19-15-29-25-39-4-46-59-48-57-78-50-84-81-60-85-67-61-52-40-64-65-74-56-62-79-69-77-58-55-83-66-92-54-86-89-53-71-68-88-87-76-63-93-72-95-75-80-82-99-96-97-94-90-70-91-73-98-51-
Generando respuestas para Prompt 2 / Conjunto 9
38-44-25-29-3-35-45-1-27-5-17-46-43-8-2-12-9-39-28-41-15-20-37-11-6-22-16-4-31-49-26-23-19-21-48-42-33-24-32-13-40-14-18-36-47-10-0-34-7-30-51-75-81-50-53-55-95-60-73-52-54-63-71-66-77-67-86-74-65-78-59-76-72-56-69-61-58-57-79-64-68-80-87-98-84-96-89-93-88-82-91-97-70-83-94-99-92-62-85-90-
Generando respuestas para Prompt 2 / Conjunto 10
21-19-3-2-37-1-12-15-35-4-41-8-14-7-13-45-44-39-20-38-28-26-46-42-31-9-29-49-25-32-30-36-18-17-43-24-33-16-34-27-22-40-6-23-0-47-5-51-10-11-76-48-63-55-60-72-50-52-82-70-79-80-68-81-91-67-58-64-59-85-75-69-73-96-65-53-77-83-54-56-57-86-66-61-94-97-93-92-87-78-71-95-62-84-88-89-99-74-90-98-
Generando respuestas para Prompt 3 / Conjunto 1
41-39-44-33-4-1-18-12-5-20-26-14-49-25-13-6-2-31-48-28-3-32-34-35-43-38-23-29-21-0-46-30-22-45-27-42-37-47-11-17-24-9-8-7-36-40-16-15-19-50-61-51-80-59-56-70-62-98-78-64-72-88-60-57-94-74-10-66-92-53-89-90-67-85-58-52-79-54-77-65-71-75-63-81-68-95-91-82-84-96-86-73-99-55-87-93-83-76-97-69-
Generando respuestas para Prompt 3 / Conjunto 2
45-33-28-6-23-32-13-9-11-24-10-17-41-7-38-20-31-1-22-39-36-4-43-26-34-2-14-35-16-37-8-40-48-12-15-21-30-29-42-0-19-5-27-47-18-46-3-25-58-44-56-61-49-70-51-53-55-66-64-88-50-57-85-60-71-81-67-79-89-86-62-52-77-87-54-76-75-80-59-92-68-74-73-82-65-69-83-91-94-72-78-95-84-90-93-97-98-96-99-63-
Generando respuestas para Prompt 3 / Conjunto 3
27-36-17-2-10-30-12-14-43-15-13-19-3-4-18-23-16-49-38-46-1-22-26-6-8-35-24-0-20-11-5-41-32-47-42-28-9-37-34-31-25-45-48-33-7-29-21-39-44-40-56-64-50-61-52-57-54-66-53-87-62-59-83-58-55-74-80-51-68-78-73-63-65-67-89-69-79-90-77-71-60-81-82-98-76-84-91-70-86-75-72-93-95-92-85-88-94-96-97-99-
Generando respuestas para Prompt 3 / Conjunto 4
0-46-34-42-13-3-7-43-14-30-2-11-6-41-28-10-4-19-18-24-17-38-26-31-40-1-16-9-37-39-47-45-25-21-23-15-48-12-22-33-8-29-35-49-27-32-20-36-5-44-60-50-51-61-74-58-57-78-52-75-56-63-53-69-70-66-54-59-99-62-84-89-76-64-86-90-81-82-67-55-68-87-71-88-73-65-92-80-72-91-85-83-77-94-93-79-95-98-97-96-
Generando respuestas para Prompt 3 / Conjunto 5
11-18-20-0-40-10-45-9-5-44-2-24-27-15-26-39-1-8-49-31-33-25-46-6-3-34-35-13-30-47-4-41-29-36-17-43-42-21-22-23-32-16-38-37-19-28-12-48-7-14-50-54-83-52-51-53-77-57-85-55-56-62-58-71-68-59-66-60-64-65-86-69-90-76-96-84-88-70-72-79-61-73-93-82-89-91-67-75-97-87-74-81-95-80-98-92-78-63-99-94-
Generando respuestas para Prompt 3 / Conjunto 6
38-46-34-2-15-8-3-21-5-23-41-26-14-0-12-47-17-33-44-25-22-6-18-49-4-1-30-13-29-45-16-20-24-7-35-39-43-28-11-32-36-10-27-37-40-42-19-31-9-50-48-51-54-58-68-82-72-53-71-91-67-76-75-69-62-59-56-55-52-84-57-83-86-70-61-98-79-81-90-78-66-63-74-95-96-60-94-85-80-87-97-77-65-93-73-89-92-64-88-99-
Generando respuestas para Prompt 3 / Conjunto 7
28-39-47-37-48-46-42-11-1-10-40-15-41-20-13-12-8-23-45-5-49-0-22-7-36-16-21-26-34-43-27-44-29-31-9-19-4-3-35-25-38-14-6-2-33-52-32-24-18-30-17-69-54-71-62-51-79-68-74-56-76-58-81-50-93-59-55-53-80-82-65-99-63-60-98-64-61-92-86-72-89-57-66-90-85-95-84-70-77-83-75-73-67-88-97-78-96-94-87-91-
Generando respuestas para Prompt 3 / Conjunto 8
13-31-47-6-0-12-20-19-24-46-3-1-36-42-39-26-44-33-4-43-5-21-30-28-14-35-23-34-37-9-41-27-2-11-18-45-17-15-25-8-10-7-48-29-38-40-16-32-49-59-66-51-50-58-83-78-81-68-84-22-56-57-52-60-71-85-64-61-55-53-70-80-89-65-92-93-54-82-72-87-75-86-76-73-88-67-63-95-90-91-99-77-79-96-69-97-98-74-94-62-
Generando respuestas para Prompt 3 / Conjunto 9
27-17-3-12-7-25-44-29-1-45-9-13-16-46-5-21-8-40-42-41-39-49-35-37-2-43-33-11-23-24-10-31-36-38-20-22-28-15-4-14-47-34-26-19-48-0-32-30-6-18-51-50-69-53-75-81-55-72-64-61-86-78-58-54-66-57-95-79-59-80-77-60-88-62-67-52-74-56-70-83-84-73-63-87-65-93-94-76-98-82-96-99-90-97-89-85-92-68-91-71-
Generando respuestas para Prompt 3 / Conjunto 10
3-23-19-2-21-45-12-9-47-39-36-37-10-35-15-1-44-8-34-24-14-5-38-7-13-40-16-43-48-25-4-6-11-32-42-41-33-26-49-22-28-29-20-0-30-27-46-17-18-51-31-54-76-63-50-91-67-70-97-52-72-95-60-58-65-81-92-64-82-74-68-57-59-85-79-66-96-55-73-69-88-61-99-87-84-56-71-86-78-53-83-90-80-93-89-98-94-62-75-77-
Generando respuestas para Prompt 4 / Conjunto 1
41-21-29-39-14-1-26-2-13-35-25-28-22-33-38-37-40-6-8-48-49-19-7-44-3-24-15-46-23-0-10-4-9-17-45-34-5-27-12-36-18-20-47-16-11-32-43-42-30-31-59-70-56-61-52-51-60-50-72-69-75-80-74-53-57-79-66-62-78-85-63-91-71-77-88-94-73-98-55-76-54-89-67-93-64-68-58-83-90-92-99-65-84-87-96-95-81-82-97-86-
Generando respuestas para Prompt 4 / Conjunto 2
39-28-17-41-45-35-23-43-1-30-47-24-7-26-10-13-14-5-3-2-38-34-11-4-12-6-9-16-44-33-18-32-46-37-20-27-22-29-49-31-42-48-8-15-40-25-21-19-0-36-58-56-50-61-57-51-88-70-64-55-67-52-83-77-72-89-54-75-66-62-71-76-53-60-81-87-86-78-85-79-59-91-68-74-73-69-65-92-63-80-95-94-82-84-93-97-98-96-99-90-
Generando respuestas para Prompt 4 / Conjunto 3
36-17-42-27-29-2-11-31-10-0-44-30-12-32-7-14-3-22-38-1-18-19-20-5-25-13-4-21-16-23-6-47-45-41-24-35-9-37-46-33-43-15-34-48-49-39-8-40-28-58-64-52-51-60-61-50-57-55-53-70-81-66-62-74-68-78-56-71-83-59-72-54-63-93-89-90-86-73-91-76-82-26-87-92-77-75-98-88-65-69-79-80-84-85-97-95-67-96-94-99-
Generando respuestas para Prompt 4 / Conjunto 4
22-34-0-42-37-47-46-11-12-3-2-4-18-14-27-31-7-49-19-6-16-24-29-9-17-33-25-5-1-23-28-30-38-8-43-45-26-35-20-10-39-41-15-21-48-40-13-32-36-44-61-50-51-71-60-52-57-54-56-53-74-63-73-69-59-70-58-55-64-86-67-66-76-78-82-62-80-90-77-75-68-84-99-81-85-79-83-72-91-94-87-89-98-93-88-92-97-65-95-96-
Generando respuestas para Prompt 4 / Conjunto 5
11-9-18-46-20-0-40-45-34-25-8-44-10-1-39-33-12-16-3-5-14-35-17-38-29-2-13-36-7-6-15-42-19-24-27-28-48-21-26-32-23-22-43-47-37-31-4-41-53-63-52-50-59-77-83-62-57-85-61-71-54-64-68-84-80-76-49-56-51-60-65-66-70-67-86-89-82-94-93-74-87-73-55-69-79-58-97-88-72-92-91-96-75-90-30-78-81-95-98-99-
Generando respuestas para Prompt 4 / Conjunto 6
38-46-33-19-34-47-24-2-15-7-12-17-49-9-23-44-11-3-36-37-1-26-16-35-30-0-45-39-29-32-31-22-5-13-21-43-8-25-4-20-40-14-10-27-6-41-18-48-28-42-51-54-50-58-68-66-62-69-72-82-76-75-53-71-55-59-52-88-94-83-90-57-63-74-79-60-73-67-86-65-64-81-84-56-96-61-89-92-95-91-85-78-80-93-77-70-97-87-98-99-
Generando respuestas para Prompt 4 / Conjunto 7
46-39-28-42-47-37-48-31-18-1-11-20-41-15-16-9-13-45-14-19-3-25-10-21-5-27-40-22-2-12-17-7-38-23-24-32-35-6-36-43-26-44-49-34-33-0-8-4-29-52-30-54-79-74-69-50-83-56-55-57-66-72-82-93-76-71-70-53-59-62-51-63-84-88-61-60-67-58-81-68-80-65-86-75-87-99-92-64-89-90-95-96-73-98-77-91-94-85-78-97-
Generando respuestas para Prompt 4 / Conjunto 8
10-13-8-33-20-0-2-27-23-25-24-3-14-21-18-30-47-12-1-28-39-16-6-9-34-32-22-26-37-7-40-29-31-5-17-4-48-11-35-42-36-46-15-45-41-38-43-44-49-19-59-66-78-50-71-84-74-54-57-55-56-63-81-89-51-58-64-85-53-60-67-61-75-65-52-92-68-77-93-72-70-76-96-73-62-79-88-82-69-95-90-86-87-99-83-91-94-97-98-80-
Generando respuestas para Prompt 4 / Conjunto 9
44-6-7-11-17-29-3-25-27-38-16-12-46-43-2-15-31-1-8-39-28-0-20-35-5-34-36-9-40-10-33-26-4-48-37-30-21-13-23-47-18-49-32-14-24-42-22-19-41-58-45-50-57-69-72-59-51-75-62-81-70-53-67-65-64-52-56-63-73-77-66-79-60-55-92-86-76-95-68-71-87-54-84-61-83-74-89-78-93-80-98-82-97-90-85-99-88-96-94-91-
Generando respuestas para Prompt 4 / Conjunto 10
19-3-38-39-10-13-4-9-34-45-8-36-47-11-12-44-48-25-6-14-0-2-28-5-26-29-22-37-35-30-1-43-33-15-7-41-21-18-32-20-23-17-49-31-24-27-40-16-42-46-51-76-58-52-65-60-72-75-64-50-88-54-66-57-67-70-91-56-92-63-61-59-82-85-90-78-87-81-71-69-62-95-55-73-74-94-83-77-98-79-53-84-68-93-89-80-86-97-99-96-

In [ ]:
'''
dir = 'Responses/'
filenames = ['analysis_minimal.xlsx', 'analysis_normal.xlsx', 'analysis_full.xlsx']
filenames = [dir + f for f in filenames]
'''

import os

def get_files_starting_with(directory, prefix):
    """Devuelve una lista con los archivos en 'directory' que comienzan con 'prefix'."""
    return [
        os.path.join(directory, f)
        for f in os.listdir(directory)
        if f.startswith(prefix)
    ]

# Ejemplo de uso:
dir_path = "Responses/"
filenames = get_files_starting_with(dir_path, "feedback_normal")

evaluate_mul(filenames, df, eval_function="map2-simple", eval_params=None, train_set_size=100, seed=42, model="gpt-4o-mini-2024-07-18", temperature=0.1)

EVALUANDO Responses/feedback_normal.xlsx
Evaluando conjunto de prueba 1 con AJUSTE
41-9-15-46-40-33-43-13-6-1-5-12-37-4-27-14-2-36-0-49-16-29-3-30-42-21-39-25-35-48-18-26-20-10-17-44-11-38-8-45-50-24-28-51-32-7-55-69-47-34-64-72-54-58-78-61-70-59-62-75-60-67-52-74-77-53-71-57-63-80-83-68-76-22-19-82-85-81-79-73-31-91-89-56-94-66-84-92-98-88-99-23-86-90-97-87-65-93-96-95-
Parámetros obtenidos: [1.00, 1.53, 9.02]
Evaluando conjunto de prueba 2 con AJUSTE
7-26-37-20-22-1-35-10-13-29-6-31-48-41-36-27-40-17-2-14-15-49-3-19-46-42-24-18-5-9-47-16-32-8-28-30-44-4-25-38-11-33-12-34-39-0-57-23-21-53-72-60-52-50-45-85-43-86-75-59-56-64-76-67-61-58-88-66-69-63-81-80-71-55-68-77-65-84-54-70-97-83-79-82-96-73-87-51-99-93-90-62-95-91-92-94-74-78-98-89-
Parámetros obtenidos: [1.00, 1.39, 9.31]
Evaluando conjunto de prueba 3 con AJUSTE
13-49-30-33-45-36-43-40-18-12-5-0-46-2-42-6-39-23-35-48-11-34-27-32-22-26-10-8-25-19-4-41-21-24-20-1-3-44-16-9-37-14-50-15-31-29-28-61-52-57-68-17-56-75-47-72-51-58-7-70-92-66-54-82-64-38-53-78-81-79-63-73-59-62-90-67-71-60-65-55-80-89-86-94-93-76-74-85-83-87-88-91-77-95-96-69-99-97-84-98-
Parámetros obtenidos: [1.00, 1.58, 9.26]
Evaluando conjunto de prueba 4 con AJUSTE
42-28-6-14-49-39-3-1-15-34-44-16-41-33-38-27-25-10-7-8-13-9-43-5-37-48-0-47-4-20-31-12-21-23-17-29-30-2-11-36-32-35-46-24-22-19-26-50-45-40-53-57-54-52-18-58-51-59-55-80-64-77-56-81-61-71-63-84-91-79-60-78-62-72-82-76-67-92-66-86-65-94-73-83-74-85-96-69-97-75-98-87-99-93-88-70-89-90-68-95-
Parámetros obtenidos: [1.00, 2.93, 8.93]
Evaluando conjunto de prueba 5 con AJUSTE
30-11-48-0-13-21-39-26-37-24-6-42-23-17-40-18-33-7-25-2-4-31-14-41-10-35-43-15-1-5-49-29-19-44-12-20-28-8-46-22-16-27-47-9-36-45-38-34-3-32-61-58-60-72-50-55-73-59-62-56-83-54-53-51-52-74-76-65-77-75-69-67-82-68-71-84-63-57-78-90-86-64-85-70-88-96-79-66-87-80-91-81-94-99-92-95-93-89-97-98-
Parámetros obtenidos: [1.00, 1.18, 9.30]
Evaluando conjunto de prueba 6 con AJUSTE
38-33-20-2-40-34-45-31-26-32-36-9-49-0-43-37-24-11-15-18-30-8-27-21-25-13-12-44-6-16-19-1-10-4-46-5-17-22-47-42-23-29-35-39-41-28-50-7-3-56-48-14-65-54-59-87-51-67-57-89-52-60-71-66-75-53-82-55-69-80-62-58-72-83-91-77-76-73-64-74-61-86-88-79-92-94-63-96-98-97-85-70-78-84-93-68-90-95-81-99-
Parámetros obtenidos: [1.00, 1.89, 8.89]
Evaluando conjunto de prueba 7 con AJUSTE
35-1-4-22-3-8-26-36-42-11-0-37-5-45-6-34-7-20-25-24-16-47-14-27-17-2-9-41-44-10-49-15-38-18-46-21-19-29-31-40-48-12-43-30-39-32-28-33-23-13-57-51-50-69-58-72-76-67-63-61-64-70-71-52-91-53-78-54-77-84-73-75-87-85-92-68-90-81-66-60-56-89-59-79-94-88-65-62-86-96-55-99-74-83-93-95-80-82-97-98-
Parámetros obtenidos: [1.00, 1.69, 9.39]
Evaluando conjunto de prueba 8 con AJUSTE
30-48-39-35-13-1-27-45-4-25-38-9-41-0-15-21-46-10-16-43-37-34-7-33-19-24-2-6-36-42-17-8-26-11-18-23-28-22-5-3-31-14-29-12-20-49-44-52-55-40-50-47-68-53-51-78-62-65-54-83-63-60-73-82-67-77-71-70-84-56-72-80-98-58-74-57-66-75-59-89-93-87-79-61-94-88-92-86-76-91-85-81-64-90-69-96-95-32-97-99-
Parámetros obtenidos: [1.00, 1.69, 9.10]
Evaluando conjunto de prueba 9 con AJUSTE
43-27-31-47-48-36-20-45-13-6-17-21-24-19-11-0-1-12-16-30-4-15-42-5-39-37-8-26-28-32-46-41-35-49-10-23-3-7-18-22-2-29-34-44-25-9-14-33-40-38-50-54-66-62-85-57-77-52-72-69-63-51-78-60-76-71-79-56-86-58-74-61-88-91-80-59-70-73-55-67-64-75-53-82-93-87-94-68-99-95-81-96-83-98-90-65-89-84-92-97-
Parámetros obtenidos: [1.00, 1.89, 9.39]
Evaluando conjunto de prueba 10 con AJUSTE
32-28-16-41-1-46-47-23-21-2-14-38-24-3-49-27-13-8-48-45-0-15-22-9-5-10-26-18-31-4-25-36-42-12-34-30-44-20-39-40-33-29-19-7-43-37-6-17-50-35-11-57-51-72-65-53-58-83-76-85-84-56-59-87-75-71-63-69-98-70-60-54-64-74-79-77-94-78-68-89-62-82-93-92-66-61-81-80-90-52-95-99-67-55-88-86-91-73-97-96-
Parámetros obtenidos: [1.00, 0.83, 10.00]


Tabla Promedios

,prompt,spearman,macro_mse,micro_mse,mse_C1-OscarBadAnswers20,mse_C2-Nan,mse_C2-Sample100,mse_C3-Sample100,mae,r2,accuracy,precision,recall,f1
0,"{""context"": ""context.txt"", ""examples_basic"": ""examples_4G4B_basic.txt"", ""question"": ""question.txt"", ""answer"": ""answer.txt"", ""instructions"": {""score"": ""score_single.txt"", ""feedback"": ""feedback_normal.txt""}}",0.685149,0.679315,0.618668,0.584859,0.779575,0.54418,0.55455,0.586506,0.516061,0.512,0.594367,0.512,0.51526

Tabla Desviación estándar

,prompt,spearman,macro_mse,micro_mse,mse_C1-OscarBadAnswers20,mse_C2-Nan,mse_C2-Sample100,mse_C3-Sample100,mae,r2,accuracy,precision,recall,f1
0,"{""context"": ""context.txt"", ""examples_basic"": ""examples_4G4B_basic.txt"", ""question"": ""question.txt"", ""answer"": ""answer.txt"", ""instructions"": {""score"": ""score_single.txt"", ""feedback"": ""feedback_normal.txt""}}",0.028883,0.095554,0.077887,0.208679,0.085526,0.130652,0.14493,0.032533,0.060925,0.029933,0.034611,0.029933,0.025547

In [ ]:
dir_path = "Evals/"
filenames = get_files_starting_with(dir_path, "T_")

read_evals(filenames, normalize=True)

Tabla Promedios

,prompt,spearman,macro_mse,micro_mse,mse_C1-OscarBadAnswers20,mse_C2-Nan,mse_C2-Sample100,mse_C3-Sample100,mae,r2,accuracy,precision,recall,f1
0,"{""context"": ""context.txt"", ""examples_basic"": ""examples_4G4B_basic.txt"", ""question"": ""question.txt"", ""answer"": ""answer.txt"", ""instructions"": {""score"": ""score_single.txt"", ""feedback"": ""feedback_normal.txt""}}",0.685149,0.679315,0.068741,0.064984,0.086619,0.060464,0.061617,0.195502,0.516061,0.512000,0.594367,0.512000,0.515260
1,"{""context"": ""context.txt"", ""examples_basic"": ""examples_4G4B_basic.txt"", ""question"": ""question.txt"", ""answer"": ""answer.txt"", ""instructions"": {""score"": ""score_single.txt""}}",0.718628,0.754334,0.069140,0.087455,0.081977,0.056064,0.068586,0.176548,0.513253,0.553000,0.612237,0.553000,0.571789
2,"{""context"": ""context.txt"", ""examples_basic"": ""examples_4G4B_basic.txt"", ""question"": ""question.txt"", ""answer"": ""answer.txt"", ""instructions"": {""analysis"": ""analysis_normal.txt"", ""score"": ""score_single.txt""}}",0.657351,0.716530,0.073802,0.114330,0.085529,0.066083,0.063866,0.198017,0.480915,0.524576,0.642908,0.524576,0.542719
3,"{""context"": ""context.txt"", ""question"": ""question.txt"", ""answer"": ""answer.txt"", ""instructions"": {""score"": ""score_single.txt""}}",0.716124,0.645303,0.062182,0.052418,0.069108,0.055138,0.064517,0.182267,0.562235,0.564000,0.643373,0.564000,0.578110
4,"{""question"": ""question.txt"", ""answer"": ""answer.txt"", ""instructions"": {""score"": ""score_single.txt""}}",0.684908,0.672856,0.067666,0.087769,0.072107,0.062722,0.064555,0.190148,0.523628,0.558000,0.648960,0.558000,0.574952

Tabla Desviación estándar

,prompt,spearman,macro_mse,micro_mse,mse_C1-OscarBadAnswers20,mse_C2-Nan,mse_C2-Sample100,mse_C3-Sample100,mae,r2,accuracy,precision,recall,f1
0,"{""context"": ""context.txt"", ""examples_basic"": ""examples_4G4B_basic.txt"", ""question"": ""question.txt"", ""answer"": ""answer.txt"", ""instructions"": {""score"": ""score_single.txt"", ""feedback"": ""feedback_normal.txt""}}",0.028883,0.095554,0.008654,0.023187,0.009503,0.014517,0.016103,0.010844,0.060925,0.029933,0.034611,0.029933,0.025547
1,"{""context"": ""context.txt"", ""examples_basic"": ""examples_4G4B_basic.txt"", ""question"": ""question.txt"", ""answer"": ""answer.txt"", ""instructions"": {""score"": ""score_single.txt""}}",0.030832,0.096771,0.009466,0.051681,0.010665,0.015100,0.014272,0.012697,0.066638,0.016155,0.024772,0.016155,0.015357
2,"{""context"": ""context.txt"", ""examples_basic"": ""examples_4G4B_basic.txt"", ""question"": ""question.txt"", ""answer"": ""answer.txt"", ""instructions"": {""analysis"": ""analysis_normal.txt"", ""score"": ""score_single.txt""}}",0.033986,0.074686,0.006750,0.047031,0.012885,0.016051,0.010345,0.009721,0.047884,0.035776,0.028877,0.035776,0.032604
3,"{""context"": ""context.txt"", ""question"": ""question.txt"", ""answer"": ""answer.txt"", ""instructions"": {""score"": ""score_single.txt""}}",0.033035,0.100690,0.008669,0.026269,0.012038,0.012608,0.017096,0.012246,0.061033,0.050438,0.034248,0.050438,0.043113
4,"{""question"": ""question.txt"", ""answer"": ""answer.txt"", ""instructions"": {""score"": ""score_single.txt""}}",0.038006,0.095532,0.009467,0.051607,0.015922,0.014438,0.020879,0.013037,0.066648,0.047497,0.041295,0.047497,0.041234

In [ ]:
!zip -r results.zip Results/

  adding: Results/ (stored 0%)
  adding: Results/analysis_normal.xlsx (deflated 0%)
  adding: Results/feedback_full.xlsx (deflated 0%)
  adding: Results/feedback_full_soft.xlsx (deflated 0%)
  adding: Results/T_examples.xlsx (deflated 2%)
  adding: Results/examples_3G1B.xlsx (deflated 1%)
  adding: Results/feedback_normal.xlsx (deflated 0%)
  adding: Results/knowledge_simple.xlsx (deflated 4%)
  adding: Results/examples_4G0B.xlsx (deflated 2%)
  adding: Results/.ipynb_checkpoints/ (stored 0%)
  adding: Results/examples_1G3B.xlsx (deflated 1%)
  adding: Results/feedback_minimal.xlsx (deflated 0%)
  adding: Results/T_analysis.xlsx (deflated 0%)
  adding: Results/analysis_full.xlsx (deflated 0%)
  adding: Results/examples_0G4B.xlsx (deflated 2%)
  adding: Results/examples_4G4B.xlsx (deflated 3%)
  adding: Results/T_qa_score.xlsx (deflated 2%)
  adding: Results/examples_1G1B.xlsx (deflated 1%)
  adding: Results/T_knowledge.xlsx (deflated 1%)
  adding: Results/examples_2G2B.xlsx (deflated 2%)
  adding: Results/analysis_minimal.xlsx (deflated 0%)
  adding: Results/knowledge_detailed.xlsx (deflated 2%)
  adding: Results/qa_score.xlsx (deflated 3%)